steps:
#  - name: maven:3-jdk-8
#    entrypoint: mvn
#    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["-f ./front-end/pom.xml", "package","-Dmaven.test.skip=true","appengine:deploy"]